### ISSUE TITLE
Missing Main.xaml.vb

### ISSUE THREAD

**Issue by odogwu2018** [Revan654/Thumbnailer#1]
The file Main.xaml.vb appears to be missing

**Comment by odogwu2018** [comment]
Hi Revan654, can you add the missing file? Thanks

**Comment by Revan654** [comment]
> 
> 
> Hi Revan654, can you add the missing file? Thanks

I'm aware when I finished uploading the files, I just don't have the file anymore. It got lost somehow. The project needs a massive Re-Do. When I get some free time I will re-do the project with WPF Only and maybe move it to C#.
